const BASE_URL =
  "https://3f9e-2a0a-a547-b5f9-0-8ccc-c6f3-ffed-3be7.ngrok-free.app";
const REDIRECT_URL =
  "https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=U9Qde8rNrra4kB5QuogGBsnyeuj1&scope=read:self-assessment write:self-assessment&redirect_uri=https://tax-app-tan.vercel.app/access-detail";

const services = [
  {
    id: 1,
    name: "Artist",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
      "Business Rates",
      "Rent",
      "Gas/Electric/Water",
      "Repairs/Maintenance",
    ],
  },
  {
    id: 2,
    name: "Beauty and Personal Care Technician",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 3,
    name: "Childcare Provider",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 4,
    name: "Construction Industry Scheme (CIS)",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 5,
    name: "Creative Professional",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 6,
    name: "Delivery Driver",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 7,
    name: "E-commerce and online seller",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 8,
    name: "Entertainer",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 9,
    name: "Gardening or Landscaping",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 10,
    name: "Freelance/Consultants",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 11,
    name: "Gardening/ landscaping",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 12,
    name: "Health and Wellness Professional",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 13,
    name: "Hospitality Services",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 14,
    name: "Landlord",
    expenses: [
      "Insurance",
      "Council Tax",
      "Ground Rent",
      "Repairs/Maintenance",
      "Service Charges",
      "Legal, Management & Other professional fees",
      "Other expenses relating to letting of property",
      "Mortgage interest (residential property)",
      "Mortgage interest (commercial property)",
      "Domestic items",
      "Standard expense allowance",
    ],
  },
  {
    id: 15,
    name: "Musician",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 16,
    name: "Photographer",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 17,
    name: "Taxi Driver",
    expenses: [
      "MOT",
      "Servicing of Vehicle",
      "Taxi Licence fee",
      "Other Taxi licencing fee (i.e. Criminal Record Check)",
      "Vehicle Repairs",
      "Fuel",
      "Mileage",
      "Cleaning of vehicle",
      "Insurance",
      "Accountancy",
      "Other",
    ],
  },
  {
    id: 18,
    name: "Teacher/ private tutor",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 19,
    name: "Tradespeople/ skilled worker",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 20,
    name: "Writer",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
  {
    id: 21,
    name: "Other",
    expenses: [
      "Travel",
      "Hotel/Accomodation",
      "Insurance",
      "Advertising",
      "Equipment",
      "Software",
      "Computer/laptop/other IT accessories",
      "Telephone",
      "Accountancy",
      "Legal/Professional",
    ],
  },
];

export { BASE_URL, REDIRECT_URL,services };
